compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://go.mskelton.dev/yarn-outdated/v4"

yarnPath: .yarn/releases/yarn-4.1.1-git.20240411.hash-c64644a.cjs
