name: "[Check] remove unused messages and create PR"

on:
  workflow_dispatch:

jobs:
  translations-unused:
    runs-on: ubuntu-latest
    if: github.repository == 'trezor/trezor-suite'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TREZOR_BOT_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup Git config
        run: |
          git config --global user.name "trezor-ci"
          git config --global user.email "${{ secrets.TREZOR_BOT_EMAIL }}"

      - name: Check for unused messages and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.TREZOR_BOT_TOKEN }}
        run: yarn workspace @trezor/suite translations:list-unused --cleanup --pr
